language: python3

sudo: required

addons:
  firefox: "55.0"
  apt:
    packages:
      - python-dev

python:
  - '3.5'

before_install:
- sudo apt-get -qq update
- sudo apt-get -y install librsvg2-bin
- sudo apt-get -y install pdftk
- sudo apt-get -y install python3-pip
- sudo apt-get install python-virtualenv
- wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver

install:
- virtualenv  -p python3 ../flask_env
- source ../flask_env/bin/activate
- pip3 install -r requirements/test.txt

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

script:
- python app/main.py >> log.txt 2>&1  &
- nosetests app/tests/test.py -v --with-coverage
- python3 -m pyflakes .

deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: 4pkYD0oO2s7d6/U7NWTILF1MJSF6j+p72o2AUaDgJLPoCC/dYv3Zf/gGXg8iqu+OQC38TktvkRvKeyglJ7Ma8VE5YJceDnat9M7yjpaThyxRdNTqQJAqHcZnsgtm4pdQLaYdhOYsfv4pF1xxdthUE/bDCfgHjUwSl5Ue0Ow+ncumyc+A3YKnmXMQLTajdux/Zz1KeZ54ZkyLXhEW4OJ8ToAIDskhHEh7q9Vfc2S/SAZ+8pHQ37zQXqI7BsubMrik3pvBLPBUoV1oqUzetxCslVpNzyUllqUdsbs+mfg0X/9kQ9zT83nYwLLQ9+h3piQLLWHr6uHuhKjzdu6+5pd/9js/ChCt0DKDdImMbycnj6PYUxx3vyNtRkhSfbzP4bDdejaMUei94+XZSI+kEJ4LloHDFog1EQFQGFlbRLqMZJMK4ou8DkM1o/XsKX5Tbnax85Blc07keXo0PudNNlfKlaaa8hTPABrti7UZvKlRUO3V1Chl95v2RvF4AZg2Qyof/J1BizQte1NlomNkEIzNUWGo9wWMYDZdayxXRvIkPBH8DBVudEn9S/+eC2rx+5RnS51MRf+rZXhcBIRowusQXafMtb1zfB+epYs+yMItWQ9ioSs4FToNkLX9xsdelwtEWDfJJ+YIe8LQ0NX/X7xxX/mCp9E1cL89C9+Q55CtoQU=
  file: "all-badges.pdf"
  on:
    branch: badge-maker

after_success:
- deactivate
- 'bash <(curl -s https://codecov.io/bash)'
